# Generated by Django 4.2.7 on 2024-03-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_appuser_facebook_appuser_instagram_appuser_twitter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='facebook',
            new_name='github',
        ),
    ]
